-- Histórico central de ações do ERP, associado ao usuário autenticado.
-- Registros anteriores à aplicação desta migração permanecem sem autoria retroativa.

create table if not exists public.auditoria_acoes (
  id bigint generated by default as identity primary key,
  tabela text not null,
  registro_id uuid,
  registro_titulo text,
  acao text not null check (acao in ('criou', 'alterou', 'excluiu')),
  usuario_id uuid not null,
  usuario_nome text not null,
  usuario_email text,
  ocorrido_em timestamptz not null default now()
);

create index if not exists auditoria_acoes_registro_idx
  on public.auditoria_acoes (tabela, registro_id, ocorrido_em desc);
create index if not exists auditoria_acoes_ocorrido_idx
  on public.auditoria_acoes (ocorrido_em desc);
create index if not exists auditoria_acoes_usuario_idx
  on public.auditoria_acoes (usuario_id, ocorrido_em desc);

alter table public.auditoria_acoes enable row level security;

drop policy if exists "Pessoas autorizadas consultam auditoria" on public.auditoria_acoes;
create policy "Pessoas autorizadas consultam auditoria"
  on public.auditoria_acoes for select
  to authenticated
  using (
    (select auth.uid()) is not null
    and coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '') in ('admin', 'socio', 'colaborador', 'juridico')
  );

revoke all on public.auditoria_acoes from anon, authenticated;
grant select on public.auditoria_acoes to authenticated;
grant all on public.auditoria_acoes to service_role;
grant usage, select on sequence public.auditoria_acoes_id_seq to service_role;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create or replace function private.registrar_auditoria_erp()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  dados jsonb;
  ator_id uuid;
  ator_nome text;
  ator_email text;
  titulo text;
begin
  ator_id := auth.uid();
  if ator_id is null then
    return case when tg_op = 'DELETE' then old else new end;
  end if;

  dados := case when tg_op = 'DELETE' then to_jsonb(old) else to_jsonb(new) end;
  ator_email := nullif(auth.jwt() ->> 'email', '');
  ator_nome := coalesce(
    nullif(auth.jwt() -> 'user_metadata' ->> 'nome', ''),
    case coalesce(auth.jwt() -> 'app_metadata' ->> 'role', '')
      when 'admin' then 'Administrador sem nome cadastrado'
      when 'socio' then 'Sócio sem nome cadastrado'
      when 'juridico' then 'Jurídico sem nome cadastrado'
      else 'Colaborador sem nome cadastrado'
    end
  );
  titulo := coalesce(
    nullif(dados ->> 'titulo', ''),
    nullif(dados ->> 'nome', ''),
    nullif(dados ->> 'descricao', ''),
    nullif(dados ->> 'motoboy_nome', ''),
    nullif(dados ->> 'fornecedor_nome', ''),
    nullif(dados ->> 'chave', '')
  );

  insert into public.auditoria_acoes (
    tabela, registro_id, registro_titulo, acao,
    usuario_id, usuario_nome, usuario_email
  ) values (
    tg_table_name,
    nullif(dados ->> 'id', '')::uuid,
    left(titulo, 240),
    case tg_op when 'INSERT' then 'criou' when 'UPDATE' then 'alterou' else 'excluiu' end,
    ator_id,
    ator_nome,
    ator_email
  );

  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

revoke all on function private.registrar_auditoria_erp() from public, anon, authenticated;
grant execute on function private.registrar_auditoria_erp() to service_role;

do $$
declare
  nome_tabela text;
begin
  foreach nome_tabela in array array[
    'colaboradores', 'motoboys', 'fornecedores', 'escala',
    'pagamentos_fornecedores', 'pagamentos_motoboys', 'entregas_motoboy',
    'kanban_tarefas', 'reunioes', 'reunioes_itens',
    'contratos', 'contrato_validacoes', 'contrato_signatarios',
    'documentos_juridicos', 'demandas_juridicas'
  ] loop
    if to_regclass('public.' || nome_tabela) is not null then
      execute format('drop trigger if exists registrar_auditoria_erp on public.%I', nome_tabela);
      execute format(
        'create trigger registrar_auditoria_erp after insert or update or delete on public.%I for each row execute function private.registrar_auditoria_erp()',
        nome_tabela
      );
    end if;
  end loop;
end;
$$;
